spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:mysql://${DATABASE_HOST}:${DATABASE_PORT}/repefin?createDatabaseIfNotExist=true
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
springdoc:
  swagger-ui:
    use-root-path: true

logging:
  level:
    org:
      zalando:
        logbook:
          Logbook: TRACE
logbook:
  format.style: json
  strategy: body-only-if-status-at-least
  minimum-status: 200
  write:
    chunk-size: 1000